### ISSUE TITLE
告警被标记的策略，疑问

### ISSUE THREAD

**Issue by wkshare** [open-falcon/alarm#1]
alarm界面，告警一旦被标记为已经解决，告警就消失了。

即使实际数据已经达到阀值，告警依然不会再出现。

这个逻辑，会导致，当告警再次超过阀值时，无法被发现。

是这样吗？

![image](https://cloud.githubusercontent.com/assets/2918384/7792189/e333bc80-02e0-11e5-96d6-0a58408eaee9.png)

**Comment by UlricQin** [comment]
不是的，如果再次达到阈值触发报警，alarm dash中会再次出现

**Comment by wkshare** [comment]
@UlricQin 我标记为恢复后，告警没有再次出现。感觉跟max的配置有关，默认是3，超过3次通知后. alarm dash中就不会再出现。

**Comment by UlricQin** [comment]
max是3，意味着最大只发送3次，之后即使达到阈值也不发了。如果你修改一下max设置，改得大一点，judge就会重新发送报警，这个时候alarm dash也将再次显示未恢复的告警

**Comment by wkshare** [comment]
@UlricQin 明白了。
